# Speech-to-Text Application Configuration

# Model Selection
stt:
  provider: "whisper"

# Server Settings
server:
  host: "localhost"
  port: 8080
  python_path: "Python/.venv/bin/python3"
  script_path: "Python/transcription_server.py"

# Audio Settings
audio:
  sample_rate: 16000
  channels: 1
  format: wav
  chunk_duration: 3  # seconds

# Whisper Settings
whisper:
  model: "small"  # Change from "base" to "large"
  language: "en"
  task: "transcribe"
  temperature: 0.0

# LLM Settings
llm:
  base_url: "http://localhost:11434"
  enabled: true
  model: "g3-1b"
  temperature: 0.1
  max_tokens: 100
  prompt: null  # Use default prompt

# Hotkey Settings
hotkey:
  key_code: 37  # L key
  modifiers: ["option"]

# Logging Settings
logging:
  enabled: true
  log_file: "Logs/transcriptions.log"
  max_file_size: "10MB"
  backup_count: 5 